# Site settings
title: Monica Bui
email: buimonica14@hotmail.com
url: https://nailsmonicabui.com
subtitle: "WHERE NAILS AND SELF-DEVELOPMENT INTERSECT"
description: "Nails nail and more nails"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#111111'
  links: '#d4af37' 
  bold: '#004870'
  alt-text: '#f2f2f2'

# Footer settings
footer: Nails by Monica Bui

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: 
  - title: instagram
    url: https://instagram.com/nailsmonicabui

# Build settings
markdown: kramdown
permalink: pretty

